// This file is auto-generated. DO NOT EDIT!

export default {
  "icon__alert": "",
  "icon__arrow_left_long": "",
  "icon__arrow_left": "",
  "icon__arrow_right": "",
  "icon__arrow_up_long": "",
  "icon__calendar": "",
  "icon__chat": "",
  "icon__checkmark": "",
  "icon__chek__do_not_use": "",
  "icon__chevron_down": "",
  "icon__chevron_left": "",
  "icon__chevron_right": "",
  "icon__chevron_soft_right": "",
  "icon__chevron_up": "",
  "icon__close_thin": "",
  "icon__close": "",
  "icon__dash": "",
  "icon__data": "",
  "icon__document": "",
  "icon__edit": "",
  "icon__error": "",
  "icon__external": "",
  "icon__facebook": "",
  "icon__fatchevron_up": "",
  "icon__file_pdf": "",
  "icon__home": "",
  "icon__info": "",
  "icon__link": "",
  "icon__location": "",
  "icon__menu": "",
  "icon__pen": "",
  "icon__radioball": "",
  "icon__search": "",
  "icon__text": "",
  "icon__time": "",
  "icon__twitter": "",
  "icon__user": "",
  "icon__warning": ""
}
