// This file is auto-generated by build.mjs

export const cssVersion = "0.8.72";

export type CssVersionToken =
  | 'dev-v0'
  | 'v0'
  | 'v0.1'
  | 'v0.2'
  | 'v0.3'
  | 'v0.4'
  | 'v0.5'
  | 'v0.6'
  | 'v0.7'
  | 'v0.8';
