#!/bin/sh

# Custom hack
git config --local include.path ../.gitconfig

OUTFILE='WARNING---LSF.txt'

# echo messages to $%OUTFILE since yarn suppresses all script output during postinstall
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "This repository uses Git LFS but 'git-lfs' was not found on your path.\nSee https://git-lfs.github.com/ for more info'.\n" > "$OUTFILE"; }

sh scripts/submodules-check.sh
