#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n"; exit 2; }
git lfs pre-push "$@"

# Do foreach because `git push --recurse-submodules=on-demand`
# somehow doesn't seem to work as advertised.  Needs further testing.
# (https://git-scm.com/book/en/v2/Git-Tools-Submodules)
git submodule foreach 'git push'
